import Head from 'next/head';
import { Card, Container, Link, Row, Spacer, Text } from '@nextui-org/react';
import NextLink from 'next/link';

import { getPosts } from '../lib/api';
import { PostData } from '../types';
import { ArrowRight } from 'react-feather';

const Home = ({ posts = [] }: any) => {
  return (
    <div>
      <Head>
        <title>Next.js blog</title>
        <meta
          name="description"
          content="Generated by create next app and using NextUI as a react UI library"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container
        as="main"
        display="flex"
        direction="column"
        justify="center"
        alignItems="center"
        style={{ height: '90vh' }}
      >
        <Spacer />
        <Text h1>
          Welcome to my&nbsp;
          <Link
            href="https://nextjs.org"
            target="_blank"
            rel="noopener noreferrer"
            css={{
              textGradient: '45deg, $blue500 -20%, $pink500 50%',
            }}
          >
            Next.js&nbsp;
          </Link>
          blog
        </Text>
        <Spacer />
        <Spacer />

        {posts.results.map((post: PostData) => (
          <NextLink
            key={post.id}
            href={`/blog/${post.properties.slug.rich_text[0].plain_text}`}
            passHref
          >
            <Card
              as="a"
              css={{
                width: '100%',
                maxW: '40rem',
                mb: '1rem',
                alignItems: 'flex-start',
                display: 'flex',
                flexDirection: 'row',
                boxShadow: '$md',
                '&:hover': {
                  bg: '$accents2',
                },
              }}
            >
              <Row align="center" justify="space-between">
                <div>
                  <Text h2>{post.properties.name.title[0].plain_text}</Text>
                  <Text color="$accents6">
                    {post.properties.subtitle.rich_text[0].plain_text}
                  </Text>
                </div>
                <ArrowRight />
              </Row>
            </Card>
          </NextLink>
        ))}
      </Container>
    </div>
  );
};

export default Home;

export async function getStaticProps() {
  // Get all posts from the Notion database
  const posts: any = await getPosts();

  return {
    props: {
      posts,
    },
    revalidate: 60,
  };
}
